AWSTemplateFormatVersion: '2010-09-09'
Description: Hoge Hoge Template
Parameters:
  VpcCidr:
    Type: String
    Default: 10.103.0.0/16
    Description: ""
  AmazonProvidedDns:
    Type: String
    Default: 10.103.0.2
  PublicSubnet1Cidr:
    Type: String
    Default: 10.103.0.0/24
    Description: ""
  KeyPair:
    Description: Name of an existing EC2 KeyPair to enable SSH access to the instances
    Type: AWS::EC2::KeyPair::KeyName
  AL2Image:
    Type: AWS::EC2::Image::Id
    Default: ami-02d36247c5bc58c23
    Description: Latest version as of November 9, 2022
  AllowHTTPCidr:
    Type: String
    Default: 0.0.0.0/0
  AllowSSHCidr:
    Type: String
    Description: "http://checkip.amazonaws.com/"
  SslSubject:
    Type: String
    Default: /C=JP/ST=Hokkaido/L=Sapporo/O=Hoge/OU=Piyo/CN=iwasa20211114.com
  HosteZone:
    Type: String
    Default: iwasa20211114.com

Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VpcCidr
      EnableDnsSupport: true
      EnableDnsHostnames: true
      InstanceTenancy: default
      Tags:
      - Key: Name
        Value: iwasa-privatevpc

  PublicSubnet1:
    Type: AWS::EC2::Subnet
    DependsOn: AttachGateway
    Properties:
      MapPublicIpOnLaunch: true
      AvailabilityZone: !Select [ 0, "Fn::GetAZs": {Ref: "AWS::Region"}]
      CidrBlock: !Ref PublicSubnet1Cidr
      Tags:
      - Key: Name
        Value: iwasa-privatevpc-public-1a-subnet
      VpcId: !Ref VPC
  PublicSubnet1RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnet1
      RouteTableId: !Ref PublicRouteTable

  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
      - Key: Name
        Value: iwasa-privatevpc-igw
  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref VPC
      InternetGatewayId: !Ref InternetGateway

  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    DependsOn: AttachGateway
    Properties:
      VpcId: !Ref VPC
      Tags:
      - Key: Name
        Value: iwasa-privatevpc-public-rt
  PublicRoute:
    Type: AWS::EC2::Route
    DependsOn: AttachGateway
    Properties:
      RouteTableId: !Ref PublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway

  # Web Server
  WebServer:
    Type: AWS::EC2::Instance
    Properties:
      Tags:
        - Key: Name
          Value: iwasa-privatevpc-web
      InstanceType: t3.micro
      BlockDeviceMappings:
        - DeviceName: /dev/sda1
          Ebs:
            VolumeType: gp3
            VolumeSize: 10
            DeleteOnTermination: true
            Encrypted: true
      SubnetId: !Ref PublicSubnet1
      SecurityGroupIds:
        - !Ref WebSecurityGroup
      ImageId: !Ref AL2Image
      KeyName: !Ref KeyPair
      EbsOptimized: true
      UserData:
        Fn::Base64: !Sub
        - |
          #cloud-config
          repo_update: true
          repo_upgrade: all
          packages:
           - httpd
           - mod_ssl
           - openssl
           - php
          runcmd:
           - openssl genrsa -out ca.key 2048
           - openssl req -new -key ca.key -out ca.csr -subj "${sslsubject}"
           - openssl x509 -req -days 365 -in ca.csr -signkey ca.key -out ca.crt
           - cp -p ca.crt /etc/pki/tls/certs/
           - cp -p ca.key /etc/pki/tls/private/
           - cp -p ca.csr /etc/pki/tls/private/
           - sed -i 's/localhost/ca/g' /etc/httpd/conf.d/ssl.conf
           - service httpd start
           - chkconfig httpd on
          write_files:
          - path: /var/www/html/index.php
            permissions: 0644
            owner: root
            content: |
              <?php 
                echo "<pre>";
                var_dump($_SERVER);
                echo "</pre>"; 
              ?>
        - { sslsubject: !Ref SslSubject }
  WebSecurityGroup:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupDescription: "web server"
      GroupName: iwasa-privatevpc-web-sg
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: iwasa-privatevpc-web-sg
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: !Ref AllowHTTPCidr
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: !Ref AllowHTTPCidr
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: !Ref AllowSSHCidr

  # DNS Server
  DnsServer:
    Type: AWS::EC2::Instance
    Properties:
      Tags:
        - Key: Name
          Value: iwasa-privatevpc-dns
      InstanceType: t3.micro
      BlockDeviceMappings:
        - DeviceName: /dev/sda1
          Ebs:
            VolumeType: gp3
            VolumeSize: 10
            DeleteOnTermination: true
            Encrypted: true
      SubnetId: !Ref PublicSubnet1
      SecurityGroupIds:
        - !Ref DnsSecurityGroup
      ImageId: !Ref AL2Image
      KeyName: !Ref KeyPair
      EbsOptimized: true
      UserData:
        Fn::Base64: !Sub
        - |
          #cloud-config
          repo_update: true
          repo_upgrade: all
          packages:
           - bind
          runcmd:
           - /etc/init.d/named start
           - chkconfig named on
          write_files:
          - path: /etc/named.conf
            permissions: 0644
            owner: root
            content: |
              options {
                  listen-on-v6 port 53 { ::1; };
                  directory     "/var/named";
                  dump-file     "/var/named/data/cache_dump.db";
                  statistics-file "/var/named/data/named_stats.txt";
                  memstatistics-file "/var/named/data/named_mem_stats.txt";
                  recursing-file  "/var/named/data/named.recursing";
                  secroots-file   "/var/named/data/named.secroots";
                  allow-query     { any; };
                  recursion no;
                  dnssec-enable yes;
                  dnssec-validation yes;
                  bindkeys-file "/etc/named.root.key";
                  managed-keys-directory "/var/named/dynamic";
                  pid-file "/run/named/named.pid";
                  session-keyfile "/run/named/session.key";
                  forwarders { ${providedDns}; };
              };
              logging {
                      channel default_debug {
                              file "data/named.run";
                              severity dynamic;
                      };
              };
              zone "." IN {
                  type hint;
                  file "named.ca";
              };
              zone "${zonename}" IN {
                  type hint;
                  file "${zonename}";
              };
              include "/etc/named.rfc1912.zones";
              include "/etc/named.root.key";
          - path: /var/named/${zonename}
            permissions: 0644
            owner: root
            content: |
              $TTL      86400
              @         IN       SOA     ns01.${zonename}. (
                                          2021111401 
                                          3600
                                          3600
                                          604800
                                          86400 )
              @         IN NS ns.${zonename}.
              @         IN A ${webServerIp}
        - { zonename: !Ref HosteZone, webServerIp: !GetAtt WebServer.PrivateIp, providedDns: !Ref AmazonProvidedDns }
  DnsSecurityGroup:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupDescription: "dns server"
      GroupName: iwasa-privatevpc-dns-sg
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: iwasa-privatevpc-dns-sg
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 53
          ToPort: 53
          CidrIp: !Ref VpcCidr
        - IpProtocol: udp
          FromPort: 53
          ToPort: 53
          CidrIp: !Ref VpcCidr
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: !Ref AllowSSHCidr

  DHCPOptions:
    Type: AWS::EC2::DHCPOptions
    Properties:
      DomainNameServers:
        - !GetAtt DnsServer.PrivateIp
      Tags:
        - Key: Name
          Value: iwasa-privatevpc-dhcp
  DHCPAssociation:
    Type: AWS::EC2::VPCDHCPOptionsAssociation
    Properties:
      VpcId: !Ref VPC
      DhcpOptionsId: !Ref DHCPOptions
